version: '3'
    
services:
    web:
        image: nginx:latest
        links: 
            - db
            - php
        volumes:
            - ./:/var/www/html
            - .docker/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8084:80
            - 8184:80
            - 8284:80
            - 8384:80
            - 8044:443
        working_dir: /var/www/html

    php:
        build: 
            context: ./
            dockerfile: .docker/Dockerfile-php-fpm
        links:
            - db
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            DB_HOST: db
            REDIS_HOST: redis

    db:
        image: mysql:8.0.3
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: carspa
        ports:
            - 33084:3306

    redis:
        image: redis:3.2.11
        ports: 
            - 6384:6379